version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-official
    restart: unless-stopped
    environment:
      - DB_TYPE=sqlite
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - WEBHOOK_URL=http://localhost:5678
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - N8N_PUSH_BACKEND=websocket
      - EXECUTIONS_MODE=regular
      - QUEUE_BULL_REDIS_HOST=
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom
      - N8N_USER_FOLDER=/home/node/.n8n
      # Disable problematic features
      - N8N_DEFAULT_BINARY_DATA_MODE=default
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_RUNNERS_ENABLED=true
      - N8N_BINARY_DATA_STORAGE_PATH=/home/node/.n8n/binaryData
      # API Keys
      - LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN}
      - LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_OWNER=${GITHUB_OWNER}
      - GITHUB_REPO=${GITHUB_REPO}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n-nodes:/home/node/.n8n/custom:ro
      - ./data:/home/node/data:ro
    env_file:
      - .env.n8n

volumes:
  n8n_data:
    driver: local