version: '3.8'

# Simplified n8n setup for quick start
services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile.n8n-optimized
    container_name: n8n-main
    restart: unless-stopped
    environment:
      # Database
      - DB_TYPE=sqlite
      - DB_SQLITE_DATABASE=/data/database.sqlite
      
      # Basic auth
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      
      # Encryption
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      
      # Webhook URL
      - WEBHOOK_URL=http://localhost:5678
      - N8N_HOST=0.0.0.0
      
      # Custom nodes
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/nodes/custom
      
      # API keys from .env.n8n
      - LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN}
      - LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_OWNER=${GITHUB_OWNER}
      - GITHUB_REPO=${GITHUB_REPO}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/data
      - ./n8n-nodes:/home/node/.n8n/nodes/custom:ro
      - ./lib:/home/node/lib:ro
      - ./data:/home/node/data:ro
    env_file:
      - .env.n8n

volumes:
  n8n_data:
    driver: local