#!/bin/bash

# 最終セットアップガイド

echo "🎉 webhook-server デプロイ開始！"
echo "================================"
echo ""
echo "ビルドログ: https://railway.com/project/b76e8ddd-3f29-4f1c-9ab3-a770948a947d/service/7d5eabc6-36ad-44db-bc86-93e33506875e?id=8241f102-a250-42a8-9d39-f00a099190dd&"
echo ""

# 待機
echo "⏳ デプロイ完了まで待機中（約1-2分）..."
sleep 90

echo ""
echo "📊 デプロイ状況:"
railway status

echo ""
echo "✅ セットアップ完了チェックリスト"
echo "================================="
echo ""
echo "□ 1. 環境変数の確認（Railwayダッシュボード）"
echo "     必須項目を実際の値に更新:"
echo "     - GEMINI_API_KEY"
echo "     - LINE_CHANNEL_ACCESS_TOKEN" 
echo "     - LINE_CHANNEL_SECRET"
echo "     - GITHUB_TOKEN"
echo "     - GITHUB_OWNER"
echo ""
echo "□ 2. デプロイ確認"
echo "     URL: https://knowledge-chat2-production.up.railway.app/health"
echo "     → {\"status\":\"OK\"} が表示されればOK"
echo ""
echo "□ 3. LINE Webhook設定"
echo "     LINE Developers Console:"
echo "     - Webhook URL: https://knowledge-chat2-production.up.railway.app/webhook"
echo "     - Webhookの利用: オン"
echo "     - 「Verify」で接続確認"
echo ""
echo "□ 4. 動作テスト"
echo "     LINEアプリから以下を送信:"
echo "     - 「こんにちは」"
echo "     - 「ナンパで緊張します」"
echo "     - 「デートに誘うタイミングは？」"
echo ""
echo "📈 期待される結果:"
echo "================================="
echo "- チバスタイルの回答（「チバです。」で始まる）"
echo "- CSDSスコア60点以上"
echo "- 自然な日本語処理"
echo "- CSV知識ベースからの適切な情報取得"
echo ""
echo "🔍 トラブルシューティング:"
echo "================================="
echo "- 503エラー → デプロイ中、もう少し待つ"
echo "- Webhook検証失敗 → 環境変数を確認"
echo "- 返信がない → Railwayログを確認"
echo "- スタイルが弱い → CSDSが正しく動作しているか確認"
echo ""
echo "📚 参考資料:"
echo "- Railwayダッシュボード: https://railway.app/dashboard"
echo "- LINE Developers: https://developers.line.biz/console/"
echo "- プロジェクトREADME: ./README.md"