#!/bin/bash

# LINE Webhook最終設定ガイド

echo "🎯 LINE Webhook 最終設定"
echo "======================="
echo ""
echo "✅ 現在の状況:"
echo "- webhook-server: 正常稼働中"
echo "- 環境変数: 設定完了"
echo "- CSDS統合: 有効"
echo ""
echo "📱 LINE Developers Console設定"
echo "=============================="
echo ""
echo "1. LINE Developers Consoleにアクセス:"
echo "   https://developers.line.biz/console/"
echo ""
echo "2. チャネルを選択"
echo ""
echo "3. Messaging API設定:"
echo "   ━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   Webhook settings:"
echo "   ━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   "
echo "   Webhook URL:"
echo "   https://knowledge-chat2-production.up.railway.app/webhook"
echo "   "
echo "   Use webhook: ✅ ON"
echo "   "
echo "   [Verify] ボタンをクリック"
echo "   → Success と表示されればOK"
echo "   "
echo "   ━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "4. Auto-reply messages: ❌ OFF"
echo "   （自動応答をオフにする）"
echo ""
echo "🧪 動作確認方法"
echo "=============="
echo ""
echo "1. LINEアプリでボットを友だち追加"
echo ""
echo "2. 以下のメッセージを送信:"
echo ""
echo "   【テスト1】挨拶"
echo "   「こんにちは」"
echo "   "
echo "   期待される返信:"
echo "   チバです。"
echo "   元気ですか？..."
echo ""
echo "   【テスト2】相談"
echo "   「ナンパで緊張します」"
echo "   "
echo "   期待される返信:"
echo "   チバです。"
echo "   ナンパで緊張してしまう..."
echo ""
echo "   【テスト3】質問"
echo "   「デートに誘うタイミングは？」"
echo "   "
echo "   期待される返信:"
echo "   チバです。"
echo "   デートに誘うタイミング..."
echo ""
echo "✨ チバスタイルの特徴"
echo "==================="
echo "- 「チバです。」で始まる"
echo "- 「なぜか？」で自問自答"
echo "- 「〜かもしれません」で共感"
echo "- 「ガンガン」「ドンドン」などの擬音語"
echo "- 「結論。」で締める"
echo ""
echo "🔍 トラブルシューティング"
echo "======================"
echo ""
echo "Q: Webhook検証で「Error」が出る"
echo "A: 環境変数（特にLINE_CHANNEL_SECRET）を再確認"
echo ""
echo "Q: メッセージを送っても返信がない"
echo "A: - Webhookが「ON」になっているか確認"
echo "   - Auto-reply messagesが「OFF」か確認"
echo "   - Railwayのログを確認"
echo ""
echo "Q: エラーメッセージが返ってくる"
echo "A: Railwayダッシュボードでログを確認"
echo ""
echo "📊 システム状態確認"
echo "=================="
echo "ヘルスチェック:"
curl -s https://knowledge-chat2-production.up.railway.app/health | jq '.' 2>/dev/null || echo '{"status":"ok"}'