#!/bin/bash

# LINE Webhook設定ガイド

echo "📱 LINE Webhook 設定ガイド"
echo "=========================="
echo ""
echo "🌐 Webhook URL:"
echo "https://knowledge-chat2-production.up.railway.app/webhook"
echo ""
echo "📋 設定手順:"
echo "=========================="
echo ""
echo "1. LINE Developers Consoleにアクセス:"
echo "   https://developers.line.biz/console/"
echo ""
echo "2. プロバイダーとチャネルを選択"
echo ""
echo "3. 'Messaging API' タブをクリック"
echo ""
echo "4. Webhook設定:"
echo "   - Webhook URL: https://knowledge-chat2-production.up.railway.app/webhook"
echo "   - 'Use webhook' をオンに設定"
echo ""
echo "5. 'Verify' ボタンをクリック:"
echo "   - 成功: 'Success' と表示される"
echo "   - 失敗: 環境変数が正しく設定されているか確認"
echo ""
echo "6. 応答設定（オプション）:"
echo "   - Auto-reply messages: オフ"
echo "   - Greeting messages: オフ（または任意）"
echo ""
echo "🧪 動作テスト手順:"
echo "=========================="
echo ""
echo "1. LINEアプリでボットを友だち追加"
echo "   - QRコードまたはIDで検索"
echo ""
echo "2. テストメッセージを送信:"
echo ""
echo "   簡単なテスト:"
echo "   - 「こんにちは」"
echo "   - 「はじめまして」"
echo ""
echo "   相談系テスト:"
echo "   - 「ナンパで緊張してしまいます」"
echo "   - 「女性との会話が続きません」"
echo "   - 「デートに誘うタイミングがわかりません」"
echo ""
echo "   質問系テスト:"
echo "   - 「声かけのコツは？」"
echo "   - 「初デートはどこがいい？」"
echo "   - 「断られた時の対処法は？」"
echo ""
echo "✅ 期待される応答:"
echo "=========================="
echo ""
echo "1. 「チバです。」で始まる"
echo "2. 「なぜか？」などの自問自答が含まれる"
echo "3. 「〜かもしれません」で読者の心理を先読み"
echo "4. 「ガンガン」「ドンドン」などの擬音語"
echo "5. 「結論。」で締める"
echo ""
echo "例:"
echo "---"
echo "チバです。"
echo ""
echo "ナンパで緊張してしまう。"
echo ""
echo "よくわかります。"
echo ""
echo "なぜか？"
echo ""
echo "誰もが最初は緊張するものだからです。"
echo ""
echo "「自分には無理」と思うかもしれません。"
echo ""
echo "でも、緊張は成長の証。"
echo ""
echo "結論。"
echo "ガンガン挑戦して慣れていきましょう。"
echo "---"
echo ""
echo "🔍 トラブルシューティング:"
echo "=========================="
echo ""
echo "Q: Webhook検証が失敗する"
echo "A: - 環境変数（特にLINE_CHANNEL_SECRET）を確認"
echo "   - URLが正しいか確認"
echo "   - Railwayで再デプロイを待つ"
echo ""
echo "Q: メッセージを送っても返信がない"
echo "A: - Railwayのログを確認"
echo "   - 環境変数（特にLINE_CHANNEL_ACCESS_TOKEN）を確認"
echo "   - Webhookがオンになっているか確認"
echo ""
echo "Q: エラーメッセージが返ってくる"
echo "A: - GEMINI_API_KEYが正しいか確認"
echo "   - GITHUB_TOKEN/OWNERが正しいか確認"
echo "   - knowledge.csvファイルが存在するか確認"