#!/bin/bash

# n8n Railway デプロイ後のセットアップ

echo "🎯 n8n デプロイ後セットアップ"
echo "=============================="
echo ""

# デプロイURLの取得方法
echo "📍 Railway URLの確認:"
echo "1. Railwayダッシュボードにアクセス"
echo "   https://railway.app/dashboard"
echo ""
echo "2. プロジェクト 'pure-analysis' を選択"
echo ""
echo "3. Settings → Domains でURLを確認"
echo "   例: https://xxx.railway.app"
echo ""

# n8nセットアップ手順
echo "🔧 n8n初期セットアップ:"
echo "=============================="
echo ""
echo "1. n8nにアクセス:"
echo "   https://[your-app].railway.app"
echo ""
echo "2. ログイン:"
echo "   ユーザー名: admin"
echo "   パスワード: [設定したパスワード]"
echo ""
echo "3. ワークフローインポート:"
echo "   - 左メニューの「Workflows」をクリック"
echo "   - 「Import from File」を選択"
echo "   - n8n-workflow-full.json をアップロード"
echo ""
echo "4. ワークフローの有効化:"
echo "   - インポートしたワークフローを開く"
echo "   - 右上の「Inactive」を「Active」に切り替え"
echo ""

# LINE設定
echo "📱 LINE Webhook設定:"
echo "=============================="
echo ""
echo "1. LINE Developers Consoleにアクセス"
echo "   https://developers.line.biz/console/"
echo ""
echo "2. Messaging API設定:"
echo "   Webhook URL: https://[your-app].railway.app/webhook/line-csds-full"
echo "   Webhookの利用: オン"
echo ""
echo "3. Webhook検証:"
echo "   「Verify」ボタンをクリック"
echo "   Success表示を確認"
echo ""

# テスト手順
echo "🧪 動作テスト:"
echo "=============================="
echo ""
echo "1. LINEアプリでボットを友だち追加"
echo ""
echo "2. テストメッセージを送信:"
echo "   - 「こんにちは」"
echo "   - 「ナンパで緊張します」"
echo "   - 「デートに誘うタイミングは？」"
echo ""
echo "3. n8nで実行履歴を確認:"
echo "   Executions → All Executions"
echo ""

# トラブルシューティング
echo "❓ トラブルシューティング:"
echo "=============================="
echo ""
echo "Q: n8nにアクセスできない"
echo "A: デプロイが完了するまで数分待つ"
echo ""
echo "Q: ログインできない"
echo "A: 環境変数 N8N_BASIC_AUTH_PASSWORD を確認"
echo ""
echo "Q: Webhook検証が失敗する"
echo "A: - URLが正しいか確認"
echo "   - n8nワークフローがActiveか確認"
echo "   - LINE環境変数が正しく設定されているか確認"
echo ""
echo "Q: メッセージに返信がない"
echo "A: - n8n Executionsで実行履歴を確認"
echo "   - エラーがある場合は詳細を確認"
echo "   - 環境変数（特にGEMINI_API_KEY）を確認"

# スコアモニタリング
echo ""
echo "📊 CSDSスコアモニタリング:"
echo "=============================="
echo ""
echo "n8nの実行履歴で以下を確認できます:"
echo "- Apply CSDS Styleノードのスコア（目標: 60点以上）"
echo "- スコア内訳（vocabulary, structure, rhetoric, emotion）"
echo "- 低スコア時の自動再生成状況"
echo ""
echo "スコアが低い場合は自動的に「Enhance Low Score」ノードで"
echo "より強いチバスタイルに変換されます。"