#!/bin/bash

# Railway環境変数クイック更新ガイド

echo "🚀 Railway環境変数 クイック更新ガイド"
echo "===================================="
echo ""
echo "⚠️  重要: ローカルの.envファイルはRailwayに反映されません"
echo "    Railwayダッシュボードで直接更新する必要があります"
echo ""
echo "📝 更新手順:"
echo "===================================="
echo ""
echo "1. Railwayダッシュボードを開く:"
echo "   https://railway.app/dashboard"
echo ""
echo "2. プロジェクトとサービスを選択:"
echo "   pure-analysis → knowledge-chat2"
echo ""
echo "3. Variablesタブをクリック"
echo ""
echo "4. 以下の変数を更新:"
echo ""
echo "   LINE_CHANNEL_SECRET:"
echo "   現在: your_line_channel_secret"
echo "   更新: ed364273343f02c13ce41050cb93470a"
echo ""
echo "   その他も実際の値に更新:"
echo "   - GEMINI_API_KEY"
echo "   - LINE_CHANNEL_ACCESS_TOKEN"
echo "   - GITHUB_TOKEN"
echo "   - GITHUB_OWNER"
echo ""
echo "5. 各変数をクリックして値を貼り付け、Enterで保存"
echo ""
echo "6. 自動的に再デプロイが開始されます（1-2分）"
echo ""
echo "🔍 更新確認方法:"
echo "===================================="
echo ""
echo "再デプロイ完了後:"
echo "1. LINE Developers ConsoleでWebhook検証"
echo "2. curl https://knowledge-chat2-production.up.railway.app/health"
echo "3. LINEアプリからテストメッセージ送信"
echo ""
echo "📱 LINE Webhook URL:"
echo "https://knowledge-chat2-production.up.railway.app/webhook"