#!/bin/bash

# Railwayデプロイメントのテストスクリプト

echo "🧪 Webhook デプロイメントテスト"
echo "================================"
echo ""

# 1. ヘルスチェック
echo "📍 ヘルスチェック:"
HEALTH_RESPONSE=$(curl -s https://knowledge-chat2-production.up.railway.app/health)
echo "レスポンス: $HEALTH_RESPONSE"

if [[ "$HEALTH_RESPONSE" == *"ok"* ]]; then
    echo "✅ サーバーは正常に動作しています"
else
    echo "❌ サーバーが応答していません"
    exit 1
fi

echo ""
echo "📊 環境変数の状態:"
echo "================================"
echo ""
echo "⚠️  以下の環境変数が実際の値に更新されていません:"
echo ""
echo "1. GEMINI_API_KEY: 'your_gemini_api_key' → 実際のAPIキーに更新が必要"
echo "2. LINE_CHANNEL_ACCESS_TOKEN: 'your_line_channel_access_token' → 実際のトークンに更新が必要"
echo "3. LINE_CHANNEL_SECRET: 'your_line_channel_secret' → 実際のシークレットに更新が必要"
echo "4. GITHUB_TOKEN: 'your_github_token' → 実際のトークンに更新が必要"
echo "5. GITHUB_OWNER: 'your_github_username' → あなたのGitHubユーザー名に更新が必要"
echo ""
echo "📝 環境変数の更新方法:"
echo "================================"
echo ""
echo "方法1: Railwayダッシュボード（推奨）"
echo "1. https://railway.app/dashboard にアクセス"
echo "2. プロジェクト 'pure-analysis' をクリック"
echo "3. Service 'knowledge-chat2' をクリック"
echo "4. 'Variables' タブをクリック"
echo "5. 各変数の値をクリックして実際の値に更新"
echo "6. 'Deploy' ボタンをクリック（自動的に再デプロイされます）"
echo ""
echo "方法2: Railway CLI（上級者向け）"
echo "# 各コマンドは個別に実行する必要があります"
echo "railway login"
echo "railway link"
echo "# その後、Railwayダッシュボードで手動設定"
echo ""
echo "🔑 必要な認証情報の取得方法:"
echo "================================"
echo ""
echo "1. Gemini API Key:"
echo "   - https://makersuite.google.com/app/apikey"
echo "   - 'Create API Key' をクリック"
echo ""
echo "2. LINE Channel Access Token & Secret:"
echo "   - https://developers.line.biz/console/"
echo "   - チャネルを選択 → 'Messaging API' タブ"
echo "   - Channel access token: 発行または再発行"
echo "   - Channel secret: Basic settings タブ"
echo ""
echo "3. GitHub Personal Access Token:"
echo "   - https://github.com/settings/tokens"
echo "   - 'Generate new token (classic)' をクリック"
echo "   - repo スコープを選択"
echo ""
echo "4. GitHub Owner:"
echo "   - あなたのGitHubユーザー名（例: aiharataketo）"
echo ""
echo "⏭️  次のステップ:"
echo "================================"
echo "1. 上記の環境変数を実際の値に更新"
echo "2. Railwayが自動的に再デプロイするのを待つ（約1-2分）"
echo "3. LINE Webhook URLを設定"
echo "4. 動作テストを実施"