#!/bin/bash

# Railway環境変数更新スクリプト

echo "🔧 Railway環境変数を更新します"
echo "================================"
echo ""
echo "以下のコマンドをRailwayダッシュボードまたはCLIで実行してください:"
echo ""
echo "# n8n設定の追加"
echo "N8N_API_ENABLED=true"
echo "N8N_RUNNERS_ENABLED=true"
echo "N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false"
echo ""
echo "# 実際の値に更新が必要な項目"
echo "GEMINI_API_KEY=実際のAPIキー"
echo "LINE_CHANNEL_ACCESS_TOKEN=実際のトークン"
echo "LINE_CHANNEL_SECRET=実際のシークレット"
echo "GITHUB_TOKEN=実際のGitHubトークン"
echo "GITHUB_OWNER=あなたのGitHubユーザー名"
echo ""
echo "Railway CLIでの設定方法:"
echo "1. railway login"
echo "2. railway link"
echo "3. 各変数を手動で設定するか、Railwayダッシュボードで設定"
echo ""
echo "Railwayダッシュボードでの設定方法:"
echo "1. https://railway.app/dashboard"
echo "2. プロジェクト 'pure-analysis' を選択"
echo "3. Service 'knowledge-chat2' を選択"
echo "4. Variables タブで環境変数を追加/更新"